---
- name: Deploy Puppet Agent 8 on RHEL 9
  hosts: all
  vars_files:
    - /etc/ansible/vault.yml
  become: yes
  
  tasks:
    - name: Install Puppet Agent 8
      include_role:
        name: deploypuppetagent8

