---
- hosts: servers
  become: true
  vars_files:
    - group_vars/servers/vault.yml

  tasks:
    - name: Install Docker for Debian
      block:
        - name: Update all packages
          apt:
            update_cache: yes
            upgrade: yes

        - name: Install required packages
          apt:
            name: 
              - apt-transport-https 
              - ca-certificates 
              - curl 
              - gnupg 
              - lsb-release
            state: latest

        - name: Check if Docker GPG key exists
          stat:
            path: /usr/share/keyrings/docker-archive-keyring.gpg
          register: docker_gpg_key

        - name: Add Docker GPG key
          shell: curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
          when: not docker_gpg_key.stat.exists

        - name: Check if Docker repo exists
          shell: grep -Ril "download.docker.com" /etc/apt/sources.list.d/
          register: docker_repo
          changed_when: false
          failed_when: false

        - name: Set up Docker repository
          shell: echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          when: "'download.docker.com' not in docker_repo.stdout"

        - name: Install Docker CE
          apt: 
            update_cache: yes
            name: 
              - docker-ce 
              - docker-ce-cli
              - containerd.io 
            state: latest
      when: ansible_distribution == "Debian"

    - name: Install Docker for Ubuntu
      block:
        - name: Update all packages
          apt:
            update_cache: yes
            upgrade: yes

        - name: Install required packages
          apt:
            name: 
              - apt-transport-https 
              - ca-certificates 
              - curl 
              - gnupg 
              - lsb-release
            state: latest

        - name: Check if Docker GPG key exists
          stat:
            path: /usr/share/keyrings/docker-archive-keyring.gpg
          register: docker_gpg_key

        - name: Add Docker GPG key
          shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
          when: not docker_gpg_key.stat.exists

        - name: Check if Docker repo exists
          shell: grep -Ril "download.docker.com" /etc/apt/sources.list.d/
          register: docker_repo
          changed_when: false
          failed_when: false

        - name: Set up Docker repository
          shell: echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          when: "'download.docker.com' not in docker_repo.stdout"

        - name: Install Docker CE
          apt: 
            update_cache: yes
            name: 
              - docker-ce 
              - docker-ce-cli
              - containerd.io 
            state: latest
      when: ansible_distribution == "Ubuntu"

