---
- hosts: servers
  user: devops
  become: yes
  vars:
    public_key: ~/.ssh/id_rsa.pub
  vars_files:
    - group_vars/servers/vault.yml

  tasks:
    - name: Include Debian family specific roles (Ubuntu/Debian)
      include_role:
        name: "{{ item }}"
      loop:
        - common
        - ufw
        - user
        - ssh
        - unattended-upgrades
      when: ansible_distribution == "Debian"

    - name: Include RedHat family specific roles (RedHat/CentOS/Fedora)
      include_role:
        name: "{{ item }}"
      loop:
        - common
        - firewalld
        - user
        - ssh
      when: ansible_distribution ==  'RedHat'
